In [1]:
data_list = [1,2,3]

In [2]:
data_list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
arr = np.array(data_list)

In [5]:
arr

array([1, 2, 3])

In [7]:
data_list2 = [[10, 20, 30],[40,50,60],[70,80,90]]

In [9]:
arr2 = np.array(data_list2)

In [10]:
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [11]:
arr3 = np.array([1,2,3,4,5])

In [12]:
arr3

array([1, 2, 3, 4, 5])

In [13]:
arr3[0]

1

In [14]:
arr3[4]

5

In [15]:
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [16]:
arr2[2,2]

90

In [17]:
arr2[0,1]

20

In [18]:
arr2[5,5]

IndexError: index 5 is out of bounds for axis 0 with size 3

In [19]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [20]:
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [24]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
np.linspace(0,300,5) #300'ü 5 parçaya böler

array([  0.,  75., 150., 225., 300.])

In [27]:
np.linspace(0,1,6) #1'i 6 parçaya böler

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [28]:
np.eye(6) #6'ya 6'lık bir matris oluşturup diagonallerde 1 değeri verecek

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [31]:
np.random.randint(0,10) #0 ile 10 arasında rastgele bir değer döner

4

In [32]:
np.random.randint(15)

8

In [33]:
np.random.randint(1,10,5) #1 ile 10 arasında 5 değer dönüp bir array içinde depolar

array([7, 8, 7, 8, 3])

In [34]:
np.random.rand(5) #0 ile 1 arasında 5 değer üretip bir arrayde depolar.

array([0.71455372, 0.82711963, 0.60287193, 0.21275885, 0.90925058])

In [36]:
np.random.randn(5) # Bu sefer 0'ın etrafında Gaussian distribution yaparak değerleri oluşturur.

array([ 0.5555881 ,  0.93623397, -0.74273865, -0.7481389 ,  1.1072814 ])

In [37]:
arr = np.arange(25)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [40]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
arr.reshape(4,5)

ValueError: cannot reshape array of size 25 into shape (4,5)

In [42]:
newArray = np.random.randint(1,100,10)

In [43]:
newArray

array([39, 99, 60, 96, 25, 82, 78, 24,  8, 78])

In [44]:
newArray.max()

99

In [45]:
newArray.min()

8

In [46]:
newArray.sum()

589

In [47]:
newArray.mean()

58.9

In [48]:
newArray.argmax() #En büyük sayının hangi indexte olduğunu verir.

1

In [49]:
newArray.argmin() #En küçük sayının hangi indexte olduğunu verir.

8

In [50]:
#Matrisler üzerinde determinant işlemini bulmaya çalışalım:

In [51]:
detArray = np.random.randint(1,100,25)

In [52]:
detArray

array([56, 54, 38, 38, 87, 45, 27, 25, 17, 44,  5, 32, 90, 28, 44, 86, 77,
       31, 10, 93, 82, 14, 52, 87, 51])

In [53]:
detArray = detArray.reshape(5,5)

In [54]:
detArray

array([[56, 54, 38, 38, 87],
       [45, 27, 25, 17, 44],
       [ 5, 32, 90, 28, 44],
       [86, 77, 31, 10, 93],
       [82, 14, 52, 87, 51]])

In [55]:
np.linalg.det(detArray)

-115773979.99999961

In [57]:
detArray2 = np.array([[1,2],[3,4]])

In [58]:
detArray2

array([[1, 2],
       [3, 4]])

In [59]:
np.linalg.det(detArray2)

-2.0000000000000004

In [60]:
round(np.linalg.det(detArray2))

-2