In [1]:
import numpy as np

In [4]:
arr = np.arange(1,10)

In [5]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr[1]

2

In [7]:
arr[3]

4

In [8]:
arr[1:5]

array([2, 3, 4, 5])

In [9]:
arr[:4]

array([1, 2, 3, 4])

In [11]:
arr[0:4]

array([1, 2, 3, 4])

In [12]:
arr[::2]

array([1, 3, 5, 7, 9])

In [13]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr[:3]

array([1, 2, 3])

In [15]:
arr[:3] = 25

In [16]:
arr

array([25, 25, 25,  4,  5,  6,  7,  8,  9])

In [17]:
arr = np.arange(1,10)

In [18]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr2 = arr

In [20]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr2[:3] = 100

In [22]:
arr2

array([100, 100, 100,   4,   5,   6,   7,   8,   9])

In [23]:
arr

array([100, 100, 100,   4,   5,   6,   7,   8,   9])

In [24]:
arr = np.arange(1,10)

In [25]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
arr2 = arr.copy()

In [27]:
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr2[:3] = 25

In [29]:
arr2

array([25, 25, 25,  4,  5,  6,  7,  8,  9])

In [30]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
newArray = np.arange(1,21)

In [32]:
newArray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [33]:
newArray.reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [34]:
newArray.reshape(10,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [35]:
newArray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [36]:
newArray = newArray.reshape(5,4)

In [37]:
newArray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [38]:
newArray[0,0]

1

In [39]:
newArray[:,:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18]])

In [40]:
newArray[:3,:3]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [41]:
newArray[:2,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [42]:
newArray[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [43]:
arr = np.arange(1,11)

In [44]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
arr > 3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [46]:
booleanArray = arr > 3

In [47]:
arr[booleanArray]

array([ 4,  5,  6,  7,  8,  9, 10])

In [48]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])