In [1]:
import numpy as np #Numpy'ı Dahil Edin

In [5]:
np.ones(5) #5 tane 1 barındıran bir array oluşturun

array([1., 1., 1., 1., 1.])

In [6]:
np.zeros(5) #5 tane 0 barındıran bir array oluşturun

array([0., 0., 0., 0., 0.])

In [7]:
np.arange(2,100,2) #2'den 100'e kadar olan değerlerden 2'ye tam bölünebilenlerle bir array oluşturun

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [19]:
arr_ten = np.arange(1,6)#5 tane 10 bulunan bir array oluşturun

In [20]:
arr_ten[:6] = 10

In [21]:
arr_ten

array([10, 10, 10, 10, 10])

In [34]:
np.ones(5) * 10 #Kısa yolu 

array([10., 10., 10., 10., 10.])

In [ ]:
#1'den 16'ya kadar değer bulunduran 4x4'lük bir matris oluşturun

In [23]:
arr2 = np.arange(1,17)

In [24]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [26]:
arr2.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [35]:
np.arange(1,17).reshape(4,4)  #Kısa yolu 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [27]:
#4x4'lük bir birim matris oluşturun

In [28]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
#0 ile 5 arasında rastgele değerler üretin

In [30]:
np.random.randint(0,5)

2

In [36]:
np.random.rand() * 5 #diğer yol

1.855719049878965

In [ ]:
#5 x 5'lik bir matrisi Gaussian Distribution'a Göre (randn() fonksiyonu) değerler üreterek oluşturun

In [37]:
np.random.randn(5,5).reshape(5,5)

array([[-1.13816539, -0.66819582,  1.31549121,  0.53664101, -0.77165074],
       [ 0.64948254, -0.35135385,  1.03740143,  0.12045757, -0.36718909],
       [-0.5377502 ,  1.08286813, -0.33079686, -0.04056788,  0.97000905],
       [ 1.42609281, -0.40855747, -1.37137642, -0.34238192,  0.09415317],
       [-0.21516152,  0.21182971, -0.91166134,  1.45681884,  1.2792125 ]])

In [ ]:
#1 ile 5 arasındaki mesafeyi eşit parçalara bölerek 20'lik bir array oluşturun

In [38]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])